version: '3'
services:
  test-pyprom:
    image: marchowes/pyprom-test:2.5
    build:
      context: .
      dockerfile: Dockerfile.pyprom-test
    environment:
      - PATH=$PATH:/usr/local/bin
    entrypoint: ["make", "test"]
    volumes:
      - ./:/pyProm
    working_dir:
      /pyProm

  pyprom:
    image: marchowes/pyprom-app:2.5
    build:
      context: .
      dockerfile: Dockerfile.pyprom
    environment:
      - PATH=$PATH:/usr/local/bin
    entrypoint: ["ipython"]
    volumes:
      - ./:/pyProm
    working_dir:
      /pyProm
