version: '3'
services:
  test-pyprom:
    build:
      context: .
      dockerfile: Dockerfile.pyprom-test
    volumes:
      - ./:/pyProm
    working_dir:
      /pyProm

  pyprom:
    build:
      context: .
      dockerfile: Dockerfile.pyprom
    volumes:
      - ./:/pyProm
    working_dir:
      /pyProm
